window.siteData = {
  profile: {
    name: "告文",
    handle: "setsuna-1106",
    location: "Nanjing University",
    role: "Physics student",
    email: "zhang.haomin1106@gmail.com",
    github: "https://github.com/setsuna-1106",
    pages: "https://setsuna-1106.github.io/setsuna-1106/",
    facts: [
      ["GitHub", "@setsuna-1106"],
      ["Public Repos", "4 public repositories"],
      ["Focus", "C / TeX / TypeScript"],
    ],
  },
  projects: [
    {
      code: "C01",
      title: "Profile / Pages",
      description: "公开主页仓库 setsuna-1106：用于展示个人入口、GitHub Pages 链接和学习项目索引，当前 GitHub API 显示主语言为 CSS。",
      tags: ["CSS", "Pages", "Portfolio"],
      status: "live",
      link: "https://github.com/setsuna-1106/setsuna-1106",
    },
    {
      code: "C02",
      title: "c4phy",
      description: "计算物理主仓库：用 C 实现误差分析、数值微积分、Monte Carlo、ODE、双摆、随机行走和衰变模型，用 Python 生成图像和实验记录。",
      tags: ["C", "Physics", "Simulation", "Notes"],
      status: "active",
      link: "https://github.com/setsuna-1106/c4phy",
    },
    {
      code: "C03",
      title: "Textbook pipeline",
      description: "把中文 STEM 教材 PDF 转为英文 LaTeX PDF 的流程记录，包含 PDF 解析、术语整理、章节重建、版式校对和最终生成。",
      tags: ["TeX", "Translation", "STEM", "Workflow"],
      status: "drafting",
      link: "https://github.com/setsuna-1106/chinese-to-english-textbook",
    },
    {
      code: "C04",
      title: "Obsidian PDF progress",
      description: "Obsidian 插件，用状态栏和文件浏览器标记 PDF 阅读进度，面向教材、论文和长文档复习的持续学习流。",
      tags: ["TypeScript", "Obsidian", "Tool"],
      status: "usable",
      link: "https://github.com/setsuna-1106/obsidian-pdf-reading-progress",
    },
    {
      code: "C05",
      title: "Computational physics modules",
      description: "c4phy 中的双摆、随机行走、阻尼振动、自发衰变、球内反射等模块，作为主页和交互面板的核心学术内容。",
      tags: ["ODE", "Visualization", "Notes", "Canvas"],
      status: "active",
      link: "https://github.com/setsuna-1106/c4phy/tree/main/src",
    },
  ],
  modules: [
    {
      id: "oscillator",
      title: "Damped oscillator",
      method: "Euler / RK family",
      intensity: 0.42,
      detail: "用阻尼振子检验步长、相位误差、能量衰减和数值稳定性，适合作为实时 canvas 展示入口。",
    },
    {
      id: "walk",
      title: "Random walk",
      method: "Monte Carlo",
      intensity: 0.76,
      detail: "随机行走和扩散距离统计用于连接概率、模拟和可视化，下一步可加入自回避行走、均方位移和多样本分布。",
    },
    {
      id: "pendulum",
      title: "Double pendulum",
      method: "Nonlinear ODE",
      intensity: 0.88,
      detail: "双摆模块展示非线性系统的敏感性，用相图、角速度轨迹和动画观察初值误差的放大。",
    },
    {
      id: "decay",
      title: "Spontaneous decay",
      method: "Discrete stochastic model",
      intensity: 0.58,
      detail: "用离散随机过程近似指数衰变，对比粒子数统计、半衰期估计和连续指数曲线。",
    },
    {
      id: "difference",
      title: "Central difference",
      method: "Numerical calculus",
      intensity: 0.36,
      detail: "比较前向差分和中心差分的截断误差，观察步长变小时舍入误差与截断误差的平衡。",
    },
    {
      id: "reflection",
      title: "Ray reflection",
      method: "Geometry simulation",
      intensity: 0.64,
      detail: "把球内光线反射拆成入射方向、法向量、反射方向和边界碰撞记录，适合后续做路径可视化。",
    },
    {
      id: "textbook",
      title: "Textbook pipeline",
      method: "Document workflow",
      intensity: 0.51,
      detail: "把 PDF 解析、术语统一、英文改写、LaTeX 重排和最终校对串成可复用流程，服务大体量学习材料整理。",
    },
  ],
  notes: [
    {
      title: "Random walk and diffusion",
      label: "Monte Carlo",
      image: "assets/random-walk.png",
      alt: "Random walk diagrams and 3D walk sketch",
      size: "large",
    },
    {
      title: "Central difference",
      label: "Numerical calculus",
      image: "assets/central-difference.png",
      alt: "Forward and central numerical difference diagrams",
      size: "medium",
    },
    {
      title: "Euler step error",
      label: "ODE",
      image: "assets/euler-rule.png",
      alt: "Euler method integration diagram",
      size: "medium",
    },
    {
      title: "Linear congruent method",
      label: "Random number",
      image: "assets/linear-congruent.png",
      alt: "Linear congruent random number formula",
      size: "small",
    },
  ],
  matrix: [
    ["Error analysis", "yes", "yes", "open"],
    ["Differentiation", "yes", "yes", "yes"],
    ["Monte Carlo", "yes", "yes", "open"],
    ["Double pendulum", "yes", "yes", "yes"],
    ["Decay model", "draft", "yes", "yes"],
    ["Random number", "yes", "yes", "draft"],
    ["Ray reflection", "draft", "yes", "open"],
    ["Textbook pipeline", "yes", "open", "open"],
    ["Obsidian reading progress", "yes", "yes", "open"],
    ["Advance website", "yes", "yes", "yes"],
  ],
  tasks: [
    {
      title: "整理 c4phy 项目主页",
      area: "Website",
      status: "done",
      detail: "完成瑞士风个人网站、GitHub profile 信息、项目入口和 advance 动态版链接。",
    },
    {
      title: "补全任务统计模块",
      area: "Website",
      status: "done",
      detail: "把学习任务转换成可筛选、可自动统计的前端组件，并支持本地新增、状态切换和重置。",
    },
    {
      title: "同步 GitHub 公开仓库列表",
      area: "GitHub",
      status: "done",
      detail: "根据 GitHub API 更新为 4 个公开仓库，并移除未出现在公开列表中的项目展示。",
    },
    {
      title: "完善 ODE / nonlinear oscillations 笔记",
      area: "Notes",
      status: "doing",
      detail: "继续整理 Euler、RK2、RK4、阻尼振子与非线性振子的相位误差和稳定性观察。",
    },
    {
      title: "给随机行走加入更多可视化",
      area: "Simulation",
      status: "open",
      detail: "补充自回避行走、均方位移、扩散距离和多样本统计分布图。",
    },
    {
      title: "整理 spontaneous decay 文档",
      area: "Notes",
      status: "open",
      detail: "把离散衰变模拟和指数近似的对照写成项目说明。",
    },
    {
      title: "补充球内反射模块说明",
      area: "Simulation",
      status: "open",
      detail: "说明光线在球内反射的几何假设、边界处理和可视化输出方式。",
    },
    {
      title: "细化教材转换流程页面",
      area: "Workflow",
      status: "doing",
      detail: "把 PDF 解析、术语统一、LaTeX 重建和最终校对拆成可复用步骤。",
    },
    {
      title: "给 Obsidian 插件补使用场景",
      area: "Tooling",
      status: "open",
      detail: "补充长文档阅读、教材复习和文件浏览器进度提示的实际用例。",
    },
    {
      title: "把 advance 数据改成可迁移 JSON",
      area: "Website",
      status: "open",
      detail: "把 window.siteData 抽成独立 JSON，为以后接 API、CMS 或静态生成做准备。",
    },
    {
      title: "检查 Pages 部署内容",
      area: "GitHub",
      status: "done",
      detail: "独立 Pages 仓库已经接入个人网站，根目录主页和 advance 子站可以分别部署。",
    },
  ],
};
