window.siteData = {
  profile: {
    name: "告文",
    handle: "setsuna-1106",
    location: "Nanjing University",
    role: "Physics student",
    email: "zhang.haomin1106@gmail.com",
    github: "https://github.com/setsuna-1106",
    pages: "https://setsuna-1106.github.io/setsuna-1106/",
    facts: [
      ["GitHub", "@setsuna-1106"],
      ["Public Repos", "7 public repositories"],
      ["Focus", "C / Python / TeX"],
    ],
  },
  projects: [
    {
      code: "C01",
      title: "Profile / Pages",
      description: "个人主页与 GitHub Profile 展示入口，集中放置学习方向、项目链接和联系方式。",
      tags: ["CSS", "Pages", "Portfolio"],
      status: "live",
      link: "https://github.com/setsuna-1106/setsuna-1106",
    },
    {
      code: "C02",
      title: "c4phy",
      description: "计算物理主仓库：16 个项目统一 Makefile 构建（8 C + 2 C++/SDL2 + 6 Python 可视化），覆盖误差分析、微积分、Monte Carlo、ODE 与傅里叶分析；近期新增受扰阻尼摆、DFT 实现与双摆 C++ 重写。",
      tags: ["C", "Physics", "Simulation", "Makefile"],
      status: "active",
      link: "https://github.com/setsuna-1106/c4phy",
    },
    {
      code: "C03",
      title: "slog",
      description: "自研学习记录 CLI：一天一个 Markdown 日志，自动衔接前一天未懂项与未勾选待办；内置 review 周检视、curses TUI 浏览、git 自动快照与 stats 统计，零第三方依赖。",
      tags: ["Python", "CLI", "TUI"],
      status: "usable",
      link: "https://github.com/setsuna-1106/slog",
    },
    {
      code: "C04",
      title: "MCMCode",
      description: "数学建模竞赛代码库：回归、分类、聚类、降维、优化、预测、ODE、图论等 13 个算法模块，每个模块配可运行模板与使用指南；TOPSIS 已修复并附 demo。",
      tags: ["Python", "Docs", "Modeling"],
      status: "active",
      link: "https://github.com/setsuna-1106/MCMCode",
    },
    {
      code: "C05",
      title: "cpp_learn",
      description: "C++ 学习仓库：SDL2 图形编程、算法实现和练习源码，配合计算物理课程的数值训练。",
      tags: ["C++", "SDL2", "Algorithms"],
      status: "active",
      link: "https://github.com/setsuna-1106/cpp_learn",
    },
    {
      code: "C06",
      title: "Textbook pipeline",
      description: "把中文 STEM 教材 PDF 转为英文 LaTeX PDF 的流程记录，包含 PDF 解析、术语整理、章节重建、版式校对和最终生成。",
      tags: ["TeX", "Translation", "STEM", "Workflow"],
      status: "drafting",
      link: "https://github.com/setsuna-1106/chinese-to-english-textbook",
    },
    {
      code: "C07",
      title: "Obsidian PDF progress",
      description: "Obsidian 插件，用状态栏和文件浏览器标记 PDF 阅读进度，面向教材、论文和长文档复习的持续学习流。",
      tags: ["TypeScript", "Obsidian", "Tool"],
      status: "usable",
      link: "https://github.com/setsuna-1106/obsidian-pdf-reading-progress",
    },
    {
      code: "C08",
      title: "Computational physics modules",
      description: "c4phy 中的双摆、随机行走、阻尼振动、自发衰变、球内反射等模块，作为主页和交互面板的核心学术内容。",
      tags: ["ODE", "Visualization", "Notes", "Canvas"],
      status: "active",
      link: "https://github.com/setsuna-1106/c4phy/tree/main/project",
    },
  ],
  modules: [
    {
      id: "oscillator",
      title: "Damped oscillator",
      method: "Euler / RK family",
      intensity: 0.42,
      detail: "用阻尼振子检验步长、相位误差、能量衰减和数值稳定性，适合作为实时 canvas 展示入口。",
    },
    {
      id: "walk",
      title: "Random walk",
      method: "Monte Carlo",
      intensity: 0.76,
      detail: "随机行走和扩散距离统计用于连接概率、模拟和可视化，下一步可加入自回避行走、均方位移和多样本分布。",
    },
    {
      id: "pendulum",
      title: "Double pendulum",
      method: "Nonlinear ODE",
      intensity: 0.88,
      detail: "双摆模块展示非线性系统的敏感性，用相图、角速度轨迹和动画观察初值误差的放大。",
    },
    {
      id: "decay",
      title: "Spontaneous decay",
      method: "Discrete stochastic model",
      intensity: 0.58,
      detail: "用离散随机过程近似指数衰变，对比粒子数统计、半衰期估计和连续指数曲线。",
    },
    {
      id: "difference",
      title: "Central difference",
      method: "Numerical calculus",
      intensity: 0.36,
      detail: "比较前向差分和中心差分的截断误差，观察步长变小时舍入误差与截断误差的平衡。",
    },
    {
      id: "reflection",
      title: "Ray reflection",
      method: "Geometry simulation",
      intensity: 0.64,
      detail: "把球内光线反射拆成入射方向、法向量、反射方向和边界碰撞记录，适合后续做路径可视化。",
    },
    {
      id: "textbook",
      title: "Textbook pipeline",
      method: "Document workflow",
      intensity: 0.51,
      detail: "把 PDF 解析、术语统一、英文改写、LaTeX 重排和最终校对串成可复用流程，服务大体量学习材料整理。",
    },
  ],
  notes: [
    {
      title: "Random walk and diffusion",
      label: "Monte Carlo",
      image: "../assets/random-walk.png",
      alt: "Random walk diagrams and 3D walk sketch",
      size: "large",
    },
    {
      title: "Central difference",
      label: "Numerical calculus",
      image: "../assets/central-difference.png",
      alt: "Forward and central numerical difference diagrams",
      size: "medium",
    },
    {
      title: "Euler step error",
      label: "ODE",
      image: "../assets/euler-rule.png",
      alt: "Euler method integration diagram",
      size: "medium",
    },
    {
      title: "Linear congruent method",
      label: "Random number",
      image: "../assets/linear-congruent.png",
      alt: "Linear congruent random number formula",
      size: "small",
    },
  ],
  matrix: [
    ["Error analysis", "yes", "yes", "open"],
    ["Differentiation", "yes", "yes", "yes"],
    ["Monte Carlo", "yes", "yes", "open"],
    ["Double pendulum", "yes", "yes", "yes"],
    ["Decay model", "draft", "yes", "yes"],
    ["Random number", "yes", "yes", "draft"],
    ["Ray reflection", "draft", "yes", "open"],
    ["Textbook pipeline", "yes", "open", "open"],
    ["Obsidian reading progress", "yes", "yes", "open"],
    ["slog CLI", "yes", "yes", "open"],
  ],
  tasks: [
    {
      title: "扩展 Fourier 分析与 DFT 实现",
      area: "Notes",
      status: "doing",
      detail: "DFT 已落地，继续补频谱实验和 Python 频域可视化对照。",
    },
    {
      title: "MCM 模板赛前实战演练",
      area: "Modeling",
      status: "doing",
      detail: "13 个模块指南文档已齐，开赛前用真题把 TOPSIS、优化和预测模板串成完整解题链路。",
    },
    {
      title: "受扰阻尼摆数据对照分析",
      area: "Simulation",
      status: "open",
      detail: "RK4 + CSV 输出已就绪，补充 Euler / RK4 误差对照和能量漂移曲线。",
    },
    {
      title: "给 slog 补导出与统计增强",
      area: "Tooling",
      status: "open",
      detail: "在 review / stats 基础上增加周报导出与学习时长统计。",
    },
    {
      title: "细化教材转换流程页面",
      area: "Workflow",
      status: "doing",
      detail: "把 PDF 解析、术语统一、LaTeX 重建和最终校对拆成可复用步骤。",
    },
    {
      title: "给 Obsidian 插件补使用场景",
      area: "Tooling",
      status: "open",
      detail: "补充长文档阅读、教材复习和文件浏览器进度提示的实际用例。",
    },
    {
      title: "完善 ODE / nonlinear oscillations 笔记",
      area: "Notes",
      status: "done",
      detail: "Euler、RK2、RK4 与阻尼振子的相位误差、稳定性观察已整理进 c4phy 笔记。",
    },
    {
      title: "统一 c4phy 工程化构建",
      area: "Engineering",
      status: "done",
      detail: "16 个项目全部接入统一 Makefile，命名规范与 C/C++、Python 工作流手册已落地。",
    },
  ],
};
